# Generated by Django 4.0.3 on 2022-06-16 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0018_alter_profile_profile_picture'),
        ('awwards', '0004_alter_projects_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to='members.profile'),
        ),
    ]
